version: '3'

services:
    build_service:
        build:
          context: .
        image: todo_service

    mongodb:
        container_name: todo_mongo
        image: mongo:latest
        ports:
          - 27017:27017

    start_service:
        image: todo_service
        command:
          java -jar /usr/src/app/target/todo-service.jar --spring.profiles.active=docker
        ports:
          - 8080:8080
        links:
          - mongodb
        depends_on:
          - build_service
          - mongodb